create table users(
user_id int generated by default as identity primary key,
username varchar2(30),
password varchar2(30),
fullname varchar2(30),
phone varchar2(30)
);
CREATE TABLE admin (
    Admin_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullname varchar2(30),
    Username VARCHAR2(50) UNIQUE,
    Password VARCHAR2(50) NOT NULL
    
);
drop table admin;
CREATE TABLE sellers (
    Seller_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Username VARCHAR2(100) UNIQUE,
    Password VARCHAR2(100) NOT NULL,
    phone varchar2(30)
);



create table items(
itemid int generated by default as identity primary key,
itemname varchar2(30),
description varchar2(100),
startdate timestamp,
enddate timestamp,
initialprice int,
startingprice int,
images varchar2(255),
seller_id number references sellers(seller_id) on delete cascade);
select * from items;
create table auctions(
auctiondate timestamp not null,
bidamount int not null,
userid int references users(user_id) on delete cascade,
itemid int references items(itemid) on delete cascade,
primary key(userid,itemid));

Alter table items add (status varchar2(25));
